services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    ports:
      - "8014:8014"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "keycloak.celine.localhost:host-gateway"
      - "api.celine.localhost:host-gateway"
